version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdatavol:/var/lib/postgresql/data
  test_app:
    build: ./test_app
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./test_app/myapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdatavol: {}
