version: '3'
services:
  db:
    image: mariadb
    ports:
      - "13306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysqlvol:/var/lib/mysql
      - mysqlsock:/run/mysqld
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html:ro
  web_reminder:
    build: ./web_reminder
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - mysqlsock:/run/mysqld
      - ~/portfolio/web_reminder:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysqlvol: {}
  mysqlsock: {}
