version: '3'
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysqlvol:/var/lib/mysql
  # web:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/html:/usr/share/nginx/html:ro
  rails_mysql:
    build: ./rails_mysql
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails_mysql/myapp:/myapp
    ports:
      - "3030:3000"
    depends_on:
      - db
  # web_reminder:
  #   build: ./web_reminder
  #   command: rails s -p 3000 -b '0.0.0.0'
  #   volumes:
  #     - ~/portfolio/web_reminder:/myapp
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
volumes:
  mysqlvol: {}
