version: '3'
services:
  db:
    image: postgres
  test_app:
    build: ./test_app
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./test_app/myapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
