version: '3'
services:
  db:
    image: mariadb
    ports:
      - "13306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysqlvol:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ~/portfolio/cloud_reminder:/usr/share/nginx/html:ro
  cloud_reminder:
    build: ./cloud_reminder
    command: bundle exec unicorn_rails -c config/unicorn.rb -E development
    volumes:
      - ~/portfolio/cloud_reminder:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DB_TYPE=docker
    env_file:
      - .env
volumes:
  mysqlvol: {}

