# 基礎となるdockerイメージ作成・テスト用
version: '3'
services:
  db2:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysqlvol:/var/lib/mysql
      - mysqlsock:/run/mysqld
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
  rails_mysql:
    build: ./rails_mysql
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - mysqlsock:/run/mysqld
      - ./rails_mysql/myapp:/myapp
    ports:
      - "3030:3000"
    depends_on:
      - db2
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdatavol:/var/lib/postgresql/data
  rails_pg:
    build: ./rails_pg
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails_pg/myapp:/myapp
    ports:
      - "3031:3000"
    depends_on:
      - db
volumes:
  mysqlvol: {}
  mysqlsock: {}
